name: ML Pipeline CI

on:
  # push:
  #   branches: [ main, master  ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest great_expectations pandas scikit-learn flake8 black mypy pytest-cov psutil GPUtil setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 day5/演習3 --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 day5/演習3 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Format check with black
      run: |
        black --check day5/演習3

    - name: Run data tests
      run: |
        pytest day5/演習3/tests/test_data.py -v

    - name: Run model tests
      run: |
        pytest day5/演習3/tests/test_model.py -v

    - name: Check model performance
      run: |
        # モデルの推論精度チェック（0.75以上）
        pytest day5/演習3/tests/test_model.py::test_model_accuracy -v

        # モデルの推論時間チェック（1秒未満）
        pytest day5/演習3/tests/test_model.py::test_model_inference_time -v

        # モデルの再現性チェック
        pytest day5/演習3/tests/test_model.py::test_model_reproducibility -v

        # モデルの存在確認
        pytest day5/演習3/tests/test_model.py::test_model_exists -v

    - name: Check model stability
      run: |
        # 複数回実行時の結果の一貫性を確認
        for i in {1..5}; do
          pytest day5/演習3/tests/test_model.py::test_model_accuracy -v
        done

    - name: Check machine performance
      run: |
        # メモリ使用量の監視
        pytest day5/演習3/tests/test_performance.py::test_memory_usage -v
        # CPU使用率の監視
        pytest day5/演習3/tests/test_performance.py::test_cpu_usage -v
        # ディスク使用量の監視
        pytest day5/演習3/tests/test_performance.py::test_disk_usage -v
        # ネットワーク使用量の監視
        pytest day5/演習3/tests/test_performance.py::test_network_usage -v
        # ストレージ使用量の監視
        pytest day5/演習3/tests/test_performance.py::test_storage_usage -v
        # GPU使用率の監視
        pytest day5/演習3/tests/test_performance.py::test_gpu_usage -v
